version: '3.7'

services:
  proxy:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: ${APP_NAME}-proxy
    environment:
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - PROXY_EXT_PORT=${PROXY_EXT_PORT}
    ports:
      - ${PROXY_EXT_PORT}:80
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    container_name: ${APP_NAME}-server
    build:
      context: ./
      target: development-build-stage
      dockerfile: .docker/node/Dockerfile
      args:
        - PORT=${PORT}
    #ports:
    #  - ${PORT}:${PORT}
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - proxy
      - database
    depends_on:
      - proxy
      - database
  database:
    image: mongo
    container_name: ${APP_NAME}-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
    ports:
      - ${DB_PORT}
    command: mongod
    volumes:
      - data:/data/db
    networks:
      - backend

networks:
  backend:
    name: weriz-backend
    driver: bridge

volumes:
  data:
    driver: local

