version: '3.7'

services:
  proxy:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: ${APP_NAME}-proxy
    environment:
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - PROXY_EXT_PORT=${PROXY_EXT_PORT}
    ports:
      - ${PROXY_EXT_PORT}:80
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    container_name: ${APP_NAME}-server
    build:
      context: ./
      target: development-build-stage
      dockerfile: .docker/node/Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - database
    depends_on:
      - database
  database:
    image: mvertes/alpine-mongo
    container_name: ${APP_NAME}-db
    environment:
      - DB_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend

networks:
  backend:
    name: weriz-backend
    driver: bridge

volumes:
  data:
    driver: local
