version: '3.7'

services:
  proxy:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: ${APP_NAME}-proxy
    environment:
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - PROXY_EXT_PORT=${PROXY_EXT_PORT}
    ports:
      - ${PROXY_EXT_PORT}:80
    restart: unless-stopped
    networks:
      - backend
  server:
    container_name: ${APP_NAME}-server
    build:
      context: ./
      target: development-build-stage
      dockerfile: .docker/node/Dockerfile
      args:
        - PORT=${PORT}
    #ports:
    #  - ${PORT}:${PORT}
    restart: unless-stopped
    networks:
      - backend
    links:
      - proxy
      - database
    depends_on:
      - proxy
      - database
  database:
    image: mongo
    container_name: ${APP_NAME}-db
    environment:
      - MONGO_INITDB_BASE_USERNAME=${DB_USER}
      - MONGO_INITDB_BASE_PASSWORD=${DB_PASS}
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: mongod
    volumes:
      - ./.docker/mongo/:/docker-entrypoint-initdb.d/:ro
      - data:/data/db
      - config:/data/configdb
    networks:
      - backend
  dashboard:
    image: mongo-express
    container_name: ${APP_NAME}-dashboard
    ports:
      - ${DB_DASH_PORT}:${DB_DASH_PORT}
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_ROOT_PASS}
      - ME_CONFIG_MONGODB_SERVER=${APP_NAME}-db
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - database
    links:
      - database

networks:
  backend:
    name: weriz-backend
    driver: bridge

volumes:
  config:
    driver: local
  data:
    driver: local

